services:

  mysql-dreamshop-db:
    image: mysql:8.0
    container_name:  mysql-dreamshop-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamshop-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - dreamshop_mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  phpmyadmin-dreamshop-db:
    container_name:  phpmyadmin-dreamshopdb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8085:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-dreamshop-db
      PMA_USER: user
      PMA_PASSWORD: user123
    depends_on:
      - mysql-dreamshop-db
    restart: unless-stopped

  #redis for caching
  redis:
    image: redis:5.0.13-alpine
    container_name: dream-shop-redis
    ports:
      - "6379:6379"

volumes:
  dreamshop_mysql_data:
    driver: local