spring:
  application:
    name : dream-shop
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:5432/dream-shp
    password: user123
    driver-class-name: org.mysql.Driver
    username: user
server:
  servlet:
    context-path: '/api/v1'