spring:
  application:
    name : dream-shop
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:5432/adminapp-db
    password: user123

    username: user
server:
  servlet:
    context-path: '/api/v1'