spring:
  application:
    name : dream-shop
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dreamshop-db
    password: user123
    username: user
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

auth:
  token:
    expirationInMils : 86400000
    jwtSecret:  F/AdmdYx9fXfkYDfaItvEOLubBrOf2tlw7XbFbPX3Jo=
server:
  servlet:
    context-path: '/api/v1'


springdoc:
  api-docs:
    path: '/api-docs'

