spring:
  application:
    name : dream-shop
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: passer123
    driver-class-name: org.postgresql.Driver
    username: postgres
server:
  servlet:
    context-path: '/api/v1'