spring:
  application:
    name : dream-shop
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/adminapp-db
    password: user123

    username: user
server:
  servlet:
    context-path: '/api/v1'


springdoc:
  api-docs:
      path: '/api-docs'
swagger-ui:
    path: '/swagger-ui-custom.html'