spring:
  application:
    name : dream-shop
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/adminapp-db
    password: user123
    username: user
  servlet:
    mutlipart:
      max-files-size: 5MB
      max-request-size: 5MB

server:
  servlet:
    context-path: '/api/v1'


springdoc:
  api-docs:
      path: '/api-docs'
swagger-ui:
    path: '/swagger-ui-custom.html'