name: dream-shop
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    #install Java 17
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
        #build & skip test
      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip=true--skip-tests package --file pom.xml
        #login to docker hub with docker username & dockerhub token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUBTOKEN }} 