name: dream-shop
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  docker-job:
    runs-on: ubuntu-latest
    #install Java 17
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
        #build & skip test
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B  package
        #base configuration to run a SonarQube Cloud analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=moAllElite_dream-shop
        #login to docker hub with docker username & dockerhub token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN}}
        #Build docker Image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        #Push to docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mouniang/dream-shop:latest