name: dream-shop
on:  push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
      - name: Build with Maven
        run: mvn -B --skip-tests package --file pom.xml